#!/bin/bash
# Author: Wilson Júnior
# Laço de repetição
for server in $(cat $1); do
echo "Servidor: $server" 
senha=1;
sshpass -p $senha ssh -o "StrictHostKeyChecking no" root@$server "exit"; # Acessar o host por ssh enviando a senha guardada e 
# irá pular a verificação de chave para não precisar digitar yes quando o prompt aparecer
if [[ $? = 0 ]]; then # Verificar se comando anterior deu certo
sshpass -p $senha ssh -o "StrictHostKeyChecking no" root@$server "update-pdv.sh ";
        echo "Versão atualizada";
        else
		echo "Algo deu erro, possivel erro de chave. Tentando apagar chave...";
		sleep 2;
		ssh-keygen -f "/home/$USER/.ssh/known_hosts" -R $server;
		sleep 2;
#senha=$( dialog --stdout --title 'Senha' --inputbox 'Digite a senha do pdv:' 0 0 )
senha=1;
sshpass -p $senha ssh -o "StrictHostKeyChecking no" root@$server "exit" ;
sshpass -p $senha ssh -o "StrictHostKeyChecking no" root@$server "update-pdv.sh ";
			if [[ $? = 0 ]]; then
				echo "Versão atualizada";
sleep 2;
	        	else
	       			echo "Algo deu erro. Possivel IP errado ou Sem Rota";
				echo "Deu erro no pdv $server" >> /bin/logerros;
			fi
	fi

done
